### PR TITLE
Update add-devices-windows.md

### PR DESCRIPTION
**Pull request by LaurenMoynihan**
proposed changes from PM.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@LaurenMoynihan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@rjagiewich : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @lenewsad - We've applied the edits you requested. Is the PR ready to merge? Thanks.

**Comment by PRMerger13** [comment]
@lenewsad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lenewsad** [comment]
@ktoliver Yes I made one other change to remove a redundant word. This is set to merge with the Live branch--is that okay or should it be set to "master?" Thanks. FYI @LaurenMoynihan

**Pull request merged**
