### PR TITLE
Update how-do-i-add-devices.md

### PR DESCRIPTION
**Pull request by cekunze**
Removed the word "bring"

### CODE REVIEW

**Comment by lenewsad** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@lenewsad: I'm sorry - only the author of this article, @barlanmsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by lenewsad** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@lenewsad: I'm sorry - only the author of this article, @barlanmsft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
