### PR TITLE
DFCI management for Surface devices

### PR DESCRIPTION
**Pull request by cbrito01**
Included guidance that DFCI management for Surface devices is not supported with devices enrolled using a provisioning package.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@cbrito01 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by paolomatarazzo — APPROVED** [review]
Thank you @cbrito01 for the contribution, the change is approved

**Comment by paolomatarazzo** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @lenewsad

**Comment by lenewsad** [comment]
#sign-off

**Review by paolomatarazzo — APPROVED** [review]

**Pull request merged**
