### PR TITLE
Update autopilot-reset.md

### PR DESCRIPTION
**Pull request by LaurenMoynihan**
Added sentence per request from PM.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@LaurenMoynihan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lenewsad** [comment]
#sign-off

**Comment by lenewsad** [comment]
@LaurenMoynihan Since you're part of the MicrosoftOrg you might need to submit this through the private repo. Go ahead and sign-off though. The team will let us know if you need to reopen these in the private one. Thank you!

**Comment by Jak-MS** [comment]
@LaurenMoynihan - this is a small enough change that we'll go ahead and merge it here in the public repo, but yes, please use the private repository for future changes. thanks!

tagging @lenewsad for visibility.

**Comment by LaurenMoynihan** [comment]
hey all
what is the private repo for this?

thanks,
Lauren

**Comment by Jak-MS** [comment]
Hi @LaurenMoynihan - should be https://github.com/MicrosoftDocs/IntuneEDU-pr

**Pull request merged**
